### ISSUE TITLE
When creating a new site, auto-generated Home page blows up.

### ISSUE THREAD

**Issue by adamglenn** [wvuweb/ur-super-theme#4]
You have to "Save" the page properties for it not to blow up.

**Comment by zeroedin** [comment]
I would suggest moving that to a "how to install" section in the README.md.

**Comment by wvuwebgist** [comment]
I believe this is occurring because the site data stuff doesn't quite behave as expected. When you first create a page, it doesn't actually have an data saved for the custom site fields. So when the pages is rendered it's looking for a data field, which doesn't exist yet, so the system throws an error saying the data doesn't exist. I'm looking at a way to handle it.

**Comment by nreckart** [comment]
I believe this is occurring because the site data stuff doesn't quite behave as expected. When you first create a page, it doesn't actually have an data saved for the custom site fields. So when the pages is rendered it's looking for a data field, which doesn't exist yet, so the system throws an error saying the data doesn't exist. By saving the page properties, you're basically saving blank values for all of the data attributes, when then show up when the page is rendered.

I'm looking at a way to handle it.

**Comment by nreckart** [comment]
Custom data attributes for newly created pages **_should_** now work as expected.
